#!/bin/sh
# Run Tetrist

JAR_DIR=jar
JAR_ARCHIVE=Tetrist.jar

if ! [ -f $JAR_DIR/$JAR_ARCHIVE ]; then
    echo "Are you sure you ran \"make\" ?"
    exit 66
fi

pkill rmiregistry
pkill java
sleep 1

rmiregistry &
java -jar $JAR_DIR/$JAR_ARCHIVE "$@"
