#!/bin/sh
# Run Tetrist

MAIN=Tetrist
BYTECODE_DIR=bytecode/Tetrist

if ! [ -f "$BYTECODE_DIR/$MAIN.class"  ]; then
    echo "Are you sure you ran \"make\" ?" >&2
    exit 66
fi

killall java 2> /dev/null
killall rmiregistry 2> /dev/null
sleep 2

java -cp $BYTECODE_DIR $MAIN
